#+TITLE: The Wedding of Rocio and Adrian Martin
#+OPTIONS: toc:nil H:2 author:nil
* Processional Introductory Music

* Welcome Statement
Welcome to this day of celebration, it's great to have all of you here
to witness the union of Rocio and Adrian as wife and husband before
friends and family. Together, we will share in the joys of their wedding,
both with the outward celebration of this occasion and with an
internal appreciation for the love that surrounds us. Rocio and
Adrian, you two have the opportunity to build an amazing life
together. You are blessed to share this experience with the loved ones
gathered here to support you as you embark on this journey together.
Marriage is, truly, a magical gift. 

In the words of the novelist Mark Twain, 

#+begin_quote

Marriage makes of two fractional lives a whole, and it gives to two
purposeless lives a work [...] it gives to two questioning natures a
reason for living, and something to live for; it will give a new
gladness to the sunshine, a new fragrance to the flowers, a new beauty
to the Earth, a new mystery to life.

#+end_quote

May you all remember and cherish this ceremony, for on this day, with
love, we will forever bind Rocio and Adrian together. 

* Speak Now

If there is anyone in attendance who has cause to believe that this
couple should not be joined in marriage, we'd like to thank you for
stopping by, and remind you that the exits are in the back.

* Wedding Sermon

Marriage is more than a simple exchanging of rings or combining of
material assets. Rather, it is an indescribably powerful shared
commitment. While today I will legally bind you together, the truly
important bonds we form today are largely invisible to the world,
existing primarily in the unfilled corners of your heart. Marriage is
one of life's greatest gifts, and it is a blessing to make these
promises with your soulmate. As you hold onto one another, you will
find deeper levels of joy, happiness and peace together. Your marriage
is the foundation upon which you will build the rest of your lives
and, despite any adversity, will always be there to sustain you. 

Rocio and Adrian, take a moment to sense the tremendous amount of love
radiating throughout this space. As you stand here today before those
gathered here in your honor, and before one another, take note that
after you speak your vows this day your lives will never be the same.
Marriage, regardless of any preconceived notions you might have, has
the capacity to deepen and challenge and strengthen you and your
relationship in ways that you never thought possible. 

The joy you'll find as you pursue your shared lives will fuel you to
face head-on the challenges you'll encounter on this Earth. On your
journeys together, keep your spouse in the place of highest priority
in your heart. Learn to work together, to laugh together, and to love
together. Don't get caught up in worldly things that will draw you
apart. Instead, focus on your shared devotion and turn inward. As your
relationship strengthens you will find that you come to share a
remarkable love; one that is both abundantly given and freely
accepted. 

* Consecration

As we celebrate this bond of unity, it is important that we keep in
mind that, while this is certainly an occasion of tremendous joy, the
promises we witness here today are serious and life-altering
commitments. 

Physicist Carl Sagan once said:

#+begin_quote

The world is so exquisite with so much love and moral depth. We should
remain grateful every day for the brief but magnificent opportunity
that life provides. The sum of all our evolution, our thinking and our
accomplishments is love.

#+end_quote

It is with simultaneous feelings of elation and expressions of respect
that we proceed with this ceremony.
  
* Exchange of Vows

Rocio and Adrian, I now invite you to publicly speak your commitment
to one another.

** Bride 
*Rocio, would you please repeat after me:* 

Adrian, today I take you to be my husband; I join my life with yours.

I promise to love and to honor you; to treasure and respect you; 

I vow to be honest, loving, and faithful; 

to love you as you are, and to grow old by your side as your love and
best friend. 

I give you my hand, my heart, and my love, from this day forward.

** Groom 
*Adrian, would you please repeat after me:*

Rocio, today I take you to be my wife; I join my life with yours. 

I promise to love and to honor you; to treasure and respect you; 

I vow to be honest, loving, and faithful; 

to love you as you are, and to grow old by your side as your love and
best friend. 

I give you my hand, my heart, and my love, from this day forward.

* Declaration of Intent 

Rocio and Adrian please join hands.

Rocio, do you take Adrian to live together in the union of marriage?
To take him as your best friend and partner in life? To honor,
cherish, and love him, from this day forward, for better or worse,
for richer or poorer, in sickness and in health, for all of your
days? 

*Rocio*: I do. 

Adrian, do you take Rocio to live together in the union of marriage?
To take her as your best friend and partner in life? To honor,
cherish, and love her, from this day forward, for better or worse,
for richer or poorer, in sickness and in health, for all of your
days? 

*Adrian*: I do.

* Exchange of Rings Minister 

The wedding ring's circular shape reflects the unending power of love
– a force with no beginning and no end. You should wear these rings
proudly, and let them remind you each day of your commitment to one
another.
   
*Please repeat after me:* 

Yo, Rocio, te doy Adrian, este anillo como simbolo de mi amor.
Colocandolo en tu dedo, te entrego todo mi corazon y mi alma. Prometo
quererte por el resto de mis dias. Te entrego todo lo que soy, y
acepto todo lo que eres.

Yo, Adrian, te doy Rocio, este anillo como simbolo de mi amor.
Colocandolo en tu dedo, te entrego todo mi corazon y mi alma. Prometo
quererte por el resto de mis dias. Te entrego todo lo que soy, y
acepto todo lo que eres.

* Pronouncement 

Family and friends, by the power vested in me by the Universal Life
Church and by the state of Florida, I am pleased to pronounce Rocio
and Adrian as wife and husband, sealed together today both in law and
in love. 

* Kiss 

Adrian, the part you've been waiting for, you may now kiss your bride. 

* Presentation

Ladies and gentlemen, it is my privilege to present to you for the
first time, Mr. and Mrs. Adrian and Rocio Martin! 

* Recessional Exit Music
       
